latest

diff --git a/bin/winel b/bin/winel
--- a/bin/winel
+++ b/bin/winel
@@ -14,21 +14,28 @@ EOF
 }
 
 main() {
-    export GAME1="$HOME/.steam/steam/steamapps/common"
-    export GAME2="/mnt/speed/steamapps/common"
-
     case "$1" in
+        tribes)
+            GAMEDIR="$GAME1/Tribes/2017_T1Basic"
+            cd "$GAMEDIR" || {
+                printf '%s\n' "$GAMEDIR not found!"
+                return 1
+            }
+
+            WINEDEBUG=-all WINEARCH=win64 \
+            WINEPREFIX=~/.wine/prefixes/tribes WINEESYNC=1 \
+            wine "$GAMEDIR/Tribes.exe" > /dev/null 2>&1 &
+            ;;
         outerworlds)
             GAMEDIR="$GAME2/The Outer Worlds"
             cd "$GAMEDIR" || {
                 printf '%s\n' "$GAMEDIR not found!"
-                exit 1
+                return 1
             }
 
             WINEDEBUG=-all WINEARCH=win64 \
-            WINEPREFIX=~/.wine/prefixes/theouterworlds WINEESYNC=1 \
-            DXVK_HUD=fps \
-            wine "$GAMEDIR/TheOuterWorlds.exe" > /dev/null 2>&1
+            WINEPREFIX=~/.wine/prefixes/theouterworlds WINEESYNC=1 MANGOHUD=1 \
+            wine "$GAMEDIR/TheOuterWorlds.exe" > /dev/null 2>&1 &
             ;;
     esac
 }
